#!/usr/bin/env bash
# Cross-compile GitHub CLI for jailbroken iOS.
#
#   tools/build-payload.sh v2.100.0     (tag required; tools/resolve-version.sh picks one)
#
# Produces, in packaging/payload/:
#   gh                  the ios/arm64 executable, ldid-signed with entitlements
#   completions/_gh     zsh completion  \ generated by a host build of the same
#   completions/gh.bash bash completion / source, since we cannot run the iOS one
#   gh.LICENSE          upstream's MIT text, shipped with the binary
#   PAYLOAD.version     "<tag> <commit> <date>", read by build-deb.sh
#
# macOS only: needs Xcode (for the iPhoneOS SDK), Go, and ldid. This is the one
# step in the pipeline that cannot run on Linux, which is why it is its own
# script and its own job. See CONTRACT.md in ios-port-ci.
#
# There is no patching step here and there is no shim. Unlike a Bun or Node
# binary, `gh` is Go, and ios/arm64 is a first-class Go port -- the linker emits
# a real iOS Mach-O and every symbol it imports exists on iOS. See README.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PAYLOAD="$ROOT/packaging/payload"
UPSTREAM="https://github.com/cli/cli.git"

# clangwrap.sh and check-macho.py are shared with the other ports and live in
# realAndi/ios-port-ci. CI checks that out and points CI_TOOLS at it; locally
# tools/ci.sh clones it on first use.
CI_TOOLS="${CI_TOOLS:-$("$ROOT/tools/ci.sh")}"

# iOS 15.0 is the floor because crypto/x509 verifies chains through
# SecTrustEvaluateWithError + SecTrustCopyCertificateChain, and the latter is
# iOS 15.0+. Lower this and TLS breaks on device with a link-time-clean binary.
# clangwrap.sh passes it to clang as -mios-version-min.
export IOS_MIN=15.0

command -v go   >/dev/null || { echo "need go (brew install go)"; exit 1; }
command -v ldid >/dev/null || { echo "need ldid (brew install ldid)"; exit 1; }
xcrun --sdk iphoneos --show-sdk-path >/dev/null 2>&1 \
    || { echo "need the iPhoneOS SDK -- install Xcode and run xcode-select --switch"; exit 1; }
[ -x "$CI_TOOLS/clangwrap.sh" ] || { echo "no clangwrap.sh in CI_TOOLS ($CI_TOOLS)"; exit 1; }

VERSION="${1:?usage: $0 <upstream tag, e.g. v2.100.0>}"
case "$VERSION" in v*) ;; *) VERSION="v$VERSION" ;; esac

TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
SRC="${GH_SRC:-$TMP/cli}"

if [ -z "${GH_SRC:-}" ]; then
    echo "==> cloning cli/cli at $VERSION"
    git -c advice.detachedHead=false clone --quiet --depth 1 --branch "$VERSION" "$UPSTREAM" "$SRC"
else
    echo "==> using existing checkout at $SRC"
fi

COMMIT=$(git -C "$SRC" rev-parse HEAD)
# Upstream stamps build.Date from the commit date; match it so a rebuild of the
# same tag produces the same bytes.
DATE=$(git -C "$SRC" show -s --format=%cd --date=format:'%Y-%m-%d' HEAD)
export SOURCE_DATE_EPOCH="$(git -C "$SRC" show -s --format=%ct HEAD)"

LDFLAGS="-s -w"
LDFLAGS="$LDFLAGS -X github.com/cli/cli/v2/internal/build.Version=${VERSION#v}"
LDFLAGS="$LDFLAGS -X github.com/cli/cli/v2/internal/build.Date=$DATE"
# NOTE: internal/authflow.oauthClientID / oauthClientSecret are deliberately NOT
# injected. Upstream hardcodes the "GitHub CLI" OAuth app in flow.go and says in
# a comment that the secret is safe in version control, so the default build
# does a real `gh auth login --web` with no secrets needed at build time.

mkdir -p "$PAYLOAD/completions"

# --- host build, only to generate completions ------------------------------
# Cobra completion scripts are static text and identical whatever GOOS produced
# them, but we cannot run the iOS binary here, so a throwaway macOS build emits
# them. It is never packaged.
echo "==> host build (for completion scripts)"
( cd "$SRC" && CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 \
    go build -trimpath -ldflags "$LDFLAGS" -o "$TMP/gh-host" ./cmd/gh )
"$TMP/gh-host" completion -s zsh  > "$PAYLOAD/completions/_gh"
"$TMP/gh-host" completion -s bash > "$PAYLOAD/completions/gh.bash"
echo "    _gh ($(wc -c < "$PAYLOAD/completions/_gh" | tr -d ' ') bytes), gh.bash"

# --- the real build --------------------------------------------------------
# CC is clangwrap.sh, not clang: ios/arm64 requires external (cgo) linking, so
# it is $CC that decides what platform the Mach-O claims and which framework
# paths go into it. The default macOS clang produces a binary that links, exits
# 0, and cannot run on a phone.
echo "==> ios/arm64 build"
( cd "$SRC" && CGO_ENABLED=1 GOOS=ios GOARCH=arm64 \
    CC="$CI_TOOLS/clangwrap.sh" CXX="$CI_TOOLS/clangwrap.sh" \
    go build -trimpath -ldflags "$LDFLAGS" -o "$PAYLOAD/gh" ./cmd/gh )

echo "==> signing"
ldid "-S$PAYLOAD/entitlements.plist" "$PAYLOAD/gh"

# The only thing standing between a silent toolchain misconfiguration and a
# package that cannot launch on anybody's phone. A build that picked up the
# macOS SDK still links and still exits 0, so nothing before this notices.
echo "==> verifying the Mach-O"
python3 "$CI_TOOLS/check-macho.py" "$PAYLOAD/gh"

# MIT requires the copyright and permission notice to travel with the binary,
# and this package is the first thing in the chain that actually redistributes
# one -- upstream ships no iOS build for anyone to point at.
cp "$SRC/LICENSE" "$PAYLOAD/gh.LICENSE"

printf '%s %s %s\n' "${VERSION#v}" "$COMMIT" "$DATE" > "$PAYLOAD/PAYLOAD.version"

echo
echo "==> packaging/payload/gh  $(du -h "$PAYLOAD/gh" | cut -f1)  gh ${VERSION#v} ($COMMIT)"
echo "    next: tools/build-deb.sh"
